/* Potenlab Supabase Project — shared auth across all potenlab services */

export const projectId = "adnynafqzeznvhzaccbr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkbnluYWZxemV6bnZoemFjY2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MDA1MDgsImV4cCI6MjA5MDE3NjUwOH0.jy8v4XqQURgM4Y6-FQNyewfJxouybf_tsk7scRBLyW0"